version: "3"
services:
  nodeserver:
    container_name: node-server
    image: node:8
    hostname: node-server.test
    build: .
    ports:
      - "3000:3000"
    links:
      - couchdb

  couchdb:
    container_name: couchdb-server
    image: couchdb:latest
    hostname: couchdb-server.test
    build:
      context: .
      dockerfile: Dockerfile-couchDB
    volumes:
      - ./data:/opt/couchdb/data
      - ./data/log:/var/log
    ports:
      - "5984:5984"
# As per the following reference run line 1 and 2 in your couch db terminal
# http://docs.couchdb.org/en/2.0.0/install/index.html
# curl -X PUT http://127.0.0.1:5984/_users
# curl -X PUT http://127.0.0.1:5984/_replicator